/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rista Platform API
 * Rista Platform API provides resource oriented URLs to work with your business data. Our API uses [JSON](http://www.json.org) for request and response. API errors are returned using standard HTTP response codes.

You will need the following to work with your business data using API
* A registered and active business with Rista. Not registered? [Get it now](https://play.google.com/store/apps/details?id=com.ristaapps.business), register and activate your business
* Sales Enterprise and API licence for your business. You can purchase these licences from Account Menu
* An active API Key and Secret Key for your business. Admin can create an API Key from Access Menu.
* All API endpoints require API Key in `x-api-key` header and a [JWT](http://jwt.io/)(JSON Web Token) in `x-api-token` header

**You need to generate a new JWT api token for each request.**

Prerequisites
* API Key and Secret Key for your business, if you don't have one request admin to create one from Access Menu
* Active Sales Enterprise and API Licence

Use a JWT library to create JWT token. Refer [json web token](http://jwt.io/) for available libraries.

Token payload should include the following.

```
{"iss": "Your API Key", "iat": 1438167698, "jti": "xyz_1438167698489" }
```

Attribute   | Description                                                                          | Type    | Required
:---------: | ------------------------------------------------------------------------------------ | :-----: | :-------:
iss         | Issuer, populate with your API Key                                                   | string  | Yes
iat         | Token issue time, time since epoch in **seconds**. | integer | Yes
jti         | JWT id to uniquely identify the request, **required** for `PUT,POST,DELETE` requests | string  | No

```
e.g. using node.js jsonwebtoken library 

const jwt = require('jsonwebtoken');
const https = require('https');

const apiKey = 'YOUR API KEY';
const secretKey = 'YOUR SECRET KEY';
const tokenCreationTime = Math.floor(Date.now() / 1000);
const payload = { iss: apiKey, iat: tokenCreationTime };

//jwt library uses HS256 as default.
const token = jwt.sign(payload, secretKey);
const options = {
  host: 'api.ristaapps.com',
  path: '/v1/branch/list',
  headers: {
    'x-api-key': apiKey,
    'x-api-token': token,
    'content-type': 'application/json'
  }
};

https.get(options, function (res) { ... });
```

**Client SDK**

Use this [API specification](https://ristaapps.com/api/documentation/swagger.json) and [swagger code generator](http://swagger.io/swagger-codegen/) tool to generate client SDK for the language of your choice.


 * OpenAPI spec version: v1
 */
import type {
  DiscountTransactionResult,
  GetAnalyticsCustomSalesSummaryParams,
  GetAnalyticsDiscountTransactionsParams,
  GetAnalyticsSalesSummaryParams,
  SalesCustomSummary,
  SalesSummary
} from '../ristaPlatformAPI.schemas';

import { customInstance } from '../../lib/ristaClient';



  export const getAnalytics = () => {
/**
 * Get sales summary for a given branch on given day or month.
 * @summary Get sales summary.
 */
const getAnalyticsSalesSummary = (
    params: GetAnalyticsSalesSummaryParams,
 ) => {
      return customInstance<SalesSummary>(
      {url: `/analytics/sales/summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get custom sales summary for a given branch on given day
 * @summary Get custom sales summary.
 */
const getAnalyticsCustomSalesSummary = (
    params: GetAnalyticsCustomSalesSummaryParams,
 ) => {
      return customInstance<SalesCustomSummary>(
      {url: `/analytics/custom/sales/summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get all discount transactions. This endpoint provides few records for each call, you will need to call this endpoint multiple times to fetch all records. In each call, the presence of `lastKey` attribute indicates that there are more records to be fetched. If there exists a `lastKey` make subsequent calls with this lastKey as a query parameter.
 * @summary Get all discount transactions.
 */
const getAnalyticsDiscountTransactions = (
    params: GetAnalyticsDiscountTransactionsParams,
 ) => {
      return customInstance<DiscountTransactionResult>(
      {url: `/analytics/discount/transactions`, method: 'GET',
        params
    },
      );
    }
  return {getAnalyticsSalesSummary,getAnalyticsCustomSalesSummary,getAnalyticsDiscountTransactions}};
export type GetAnalyticsSalesSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAnalytics>['getAnalyticsSalesSummary']>>>
export type GetAnalyticsCustomSalesSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAnalytics>['getAnalyticsCustomSalesSummary']>>>
export type GetAnalyticsDiscountTransactionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAnalytics>['getAnalyticsDiscountTransactions']>>>
