/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rista Platform API
 * Rista Platform API provides resource oriented URLs to work with your business data. Our API uses [JSON](http://www.json.org) for request and response. API errors are returned using standard HTTP response codes.

You will need the following to work with your business data using API
* A registered and active business with Rista. Not registered? [Get it now](https://play.google.com/store/apps/details?id=com.ristaapps.business), register and activate your business
* Sales Enterprise and API licence for your business. You can purchase these licences from Account Menu
* An active API Key and Secret Key for your business. Admin can create an API Key from Access Menu.
* All API endpoints require API Key in `x-api-key` header and a [JWT](http://jwt.io/)(JSON Web Token) in `x-api-token` header

**You need to generate a new JWT api token for each request.**

Prerequisites
* API Key and Secret Key for your business, if you don't have one request admin to create one from Access Menu
* Active Sales Enterprise and API Licence

Use a JWT library to create JWT token. Refer [json web token](http://jwt.io/) for available libraries.

Token payload should include the following.

```
{"iss": "Your API Key", "iat": 1438167698, "jti": "xyz_1438167698489" }
```

Attribute   | Description                                                                          | Type    | Required
:---------: | ------------------------------------------------------------------------------------ | :-----: | :-------:
iss         | Issuer, populate with your API Key                                                   | string  | Yes
iat         | Token issue time, time since epoch in **seconds**. | integer | Yes
jti         | JWT id to uniquely identify the request, **required** for `PUT,POST,DELETE` requests | string  | No

```
e.g. using node.js jsonwebtoken library 

const jwt = require('jsonwebtoken');
const https = require('https');

const apiKey = 'YOUR API KEY';
const secretKey = 'YOUR SECRET KEY';
const tokenCreationTime = Math.floor(Date.now() / 1000);
const payload = { iss: apiKey, iat: tokenCreationTime };

//jwt library uses HS256 as default.
const token = jwt.sign(payload, secretKey);
const options = {
  host: 'api.ristaapps.com',
  path: '/v1/branch/list',
  headers: {
    'x-api-key': apiKey,
    'x-api-token': token,
    'content-type': 'application/json'
  }
};

https.get(options, function (res) { ... });
```

**Client SDK**

Use this [API specification](https://ristaapps.com/api/documentation/swagger.json) and [swagger code generator](http://swagger.io/swagger-codegen/) tool to generate client SDK for the language of your choice.


 * OpenAPI spec version: v1
 */
import type {
  ChangeDeliveryModeInput,
  CustomerLoyaltyObject,
  CustomerLoyaltyRedeemObjectBody,
  CustomerLoyaltyReedemResponse,
  CustomerLoyaltyReedemVerifyResponse,
  CustomerLoyaltyResponse,
  DiscountUpdateInput,
  Empty,
  GetPaymentsParams,
  GetSaleParams,
  GetSalePaymentsParams,
  GetSaleResourceParams,
  GetSalesLedgerParams,
  GetSalesPageParams,
  GetSalesParams,
  GetSalesSummaryParams,
  OfferRedeemObjectBody,
  OfflinePaymentInput,
  PartialOrderAcceptence,
  PaxCountInput,
  PaymentInput,
  PaymentsResult,
  PostSale,
  Sale,
  SaleDeliveryStatusInput,
  SaleResourceInput,
  SaleStatusInput,
  SaleTargetInput,
  SalesPageResult,
  SalesResult
} from '../ristaPlatformAPI.schemas';

import { customInstance } from '../../lib/ristaClient';



  export const getSale = () => {
/**
 * Get payments made for a given day.
 * @deprecated
 * @summary Deprecated - Get payments.
 */
const getPayments = (
    params: GetPaymentsParams,
 ) => {
      return customInstance<PaymentsResult>(
      {url: `/payments`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get sale detail for a given invoice number.
 * @summary Get sale detail.
 */
const getSale = (
    params: GetSaleParams,
 ) => {
      return customInstance<Sale>(
      {url: `/sale`, method: 'GET',
        params
    },
      );
    }
  /**
 * Save sale into your business account.
 * @summary Save sale.
 */
const postSale = (
    postSale: PostSale,
 ) => {
      return customInstance<Sale>(
      {url: `/sale`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postSale
    },
      );
    }
  /**
 * Get Current open orders for a resource i.e., table
 * @summary Get Current resource orders
 */
const getSaleResource = (
    params: GetSaleResourceParams,
 ) => {
      return customInstance<Sale[]>(
      {url: `/sale/resource`, method: 'GET',
        params
    },
      );
    }
  /**
 * Updates Sale Resource(Table)
 * @summary Update Sale Resource(Table)
 */
const postSaleResource = (
    saleResourceInput: SaleResourceInput,
 ) => {
      return customInstance<void>(
      {url: `/sale/resource`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saleResourceInput
    },
      );
    }
  /**
 * Updates Sale Pax Count
 * @summary Updates Sale Pax Count
 */
const postSaleResourcePax = (
    paxCountInput: PaxCountInput,
 ) => {
      return customInstance<void>(
      {url: `/sale/resource/pax`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: paxCountInput
    },
      );
    }
  /**
 * Updates Sale Status
 * @summary Update Sale Status
 */
const postSaleStatus = (
    saleStatusInput: SaleStatusInput,
 ) => {
      return customInstance<void>(
      {url: `/sale/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saleStatusInput
    },
      );
    }
  /**
 * Update Sale delivery status
 * @summary Update Sale delivery status
 */
const postSaleDeliveryStatus = (
    saleDeliveryStatusInput: SaleDeliveryStatusInput,
 ) => {
      return customInstance<void>(
      {url: `/sale/delivery/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saleDeliveryStatusInput
    },
      );
    }
  /**
 * Update sale with target systems information
 * @summary Update Sale with target information
 */
const postSaleTarget = (
    saleTargetInput: SaleTargetInput,
 ) => {
      return customInstance<void>(
      {url: `/sale/target`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saleTargetInput
    },
      );
    }
  /**
 * Get payments for a given invoice number.
 * @deprecated
 * @summary Deprecated - Get payments for a sale.
 */
const getSalePayments = (
    params: GetSalePaymentsParams,
 ) => {
      return customInstance<PaymentsResult>(
      {url: `/sale/payments`, method: 'GET',
        params
    },
      );
    }
  /**
 * Add payment to an existing sale.
 * @summary Add payment
 */
const postSalePayments = (
    paymentInput: PaymentInput,
 ) => {
      return customInstance<Sale>(
      {url: `/sale/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: paymentInput
    },
      );
    }
  /**
 * Customer opts to pay offline for an order.
 * @summary Offline Payment
 */
const postSalePaymentsOffline = (
    offlinePaymentInput: OfflinePaymentInput,
 ) => {
      return customInstance<Sale>(
      {url: `/sale/payments/offline`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offlinePaymentInput
    },
      );
    }
  /**
 * Apply discounts on sale.
 * @summary Apply discounts on sale.
 */
const postSaleDiscountUpdate = (
    discountUpdateInput: DiscountUpdateInput,
 ) => {
      return customInstance<Sale>(
      {url: `/sale/discount/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: discountUpdateInput
    },
      );
    }
  /**
 * Returns list of sales for a given branch on a given day.
 * @deprecated
 * @summary Deprecated - Get sales records for a given branch on a given day.
 */
const getSales = (
    params: GetSalesParams,
 ) => {
      return customInstance<SalesResult>(
      {url: `/sales`, method: 'GET',
        params
    },
      );
    }
  /**
 * Returns list of sales summary records for a given branch on a given day. This endpoint provides few records for each call, you will need to call this endpoint multiple times to fetch all records. In each call, the presence of `lastKey` attribute indicates that there are more records to be fetched. If there exists a `lastKey` make subsequent calls with this lastKey as a query parameter.
 * @summary Get sale summary records for a given branch on a given day.
 */
const getSalesSummary = (
    params: GetSalesSummaryParams,
 ) => {
      return customInstance<SalesResult>(
      {url: `/sales/summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * Returns page of detailed sale records. This endpoint provides few records for each call, you will need to call this endpoint multiple times to fetch all records. In each call, the presence of `lastKey` attribute indicates that there are more records to be fetched. If there exists a `lastKey` make subsequent calls with this lastKey as a query parameter.
 * @summary Get detailed sale records for a given branch on a given day.
 */
const getSalesPage = (
    params: GetSalesPageParams,
 ) => {
      return customInstance<SalesPageResult>(
      {url: `/sales/page`, method: 'GET',
        params
    },
      );
    }
  /**
 * Mark order item out of stock
 * @summary Partial Order Acceptence
 */
const postSaleItemOutofstock = (
    partialOrderAcceptence: PartialOrderAcceptence,
 ) => {
      return customInstance<Sale>(
      {url: `/sale/item/outofstock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: partialOrderAcceptence
    },
      );
    }
  /**
 * User can change delivery mode from pickup to delivery and ensure self-delivery
 * @summary Change mode of delivery
 */
const postSaleDeliveryMode = (
    changeDeliveryModeInput: ChangeDeliveryModeInput,
 ) => {
      return customInstance<Sale>(
      {url: `/sale/delivery/mode`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeDeliveryModeInput
    },
      );
    }
  /**
 * Returns page of detailed sale ledger records. This endpoint provides few records for each call, you will need to call this endpoint multiple times to fetch all records. In each call, the presence of `lastKey` attribute indicates that there are more records to be fetched. If there exists a `lastKey` make subsequent calls with this lastKey as a query parameter.
 * @summary Get detailed sale ledger records for a given branch on a given day.
 */
const getSalesLedger = (
    params: GetSalesLedgerParams,
 ) => {
      return customInstance<SalesPageResult>(
      {url: `/sales/ledger`, method: 'GET',
        params
    },
      );
    }
  const postSalesLoyalty = (
    customerLoyaltyObject: CustomerLoyaltyObject,
 ) => {
      return customInstance<CustomerLoyaltyResponse>(
      {url: `/sales/loyalty`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerLoyaltyObject
    },
      );
    }
  const postSalesLoyaltyRedeem = (
    customerLoyaltyRedeemObjectBody: CustomerLoyaltyRedeemObjectBody,
 ) => {
      return customInstance<CustomerLoyaltyReedemResponse>(
      {url: `/sales/loyalty/redeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerLoyaltyRedeemObjectBody
    },
      );
    }
  const postSalesLoyaltyVerifyRedeem = (
    customerLoyaltyRedeemObjectBody: CustomerLoyaltyRedeemObjectBody,
 ) => {
      return customInstance<CustomerLoyaltyReedemVerifyResponse>(
      {url: `/sales/loyalty/verifyRedeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerLoyaltyRedeemObjectBody
    },
      );
    }
  const postSalesOffers = (
    offerRedeemObjectBody: OfferRedeemObjectBody,
 ) => {
      return customInstance<Empty>(
      {url: `/sales/offers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offerRedeemObjectBody
    },
      );
    }
  const postSalesOffersRedeem = (
    offerRedeemObjectBody: OfferRedeemObjectBody,
 ) => {
      return customInstance<Empty>(
      {url: `/sales/offers/redeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offerRedeemObjectBody
    },
      );
    }
  const postSalesOffersVerifyRedeem = (
    offerRedeemObjectBody: OfferRedeemObjectBody,
 ) => {
      return customInstance<Empty>(
      {url: `/sales/offers/verifyRedeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: offerRedeemObjectBody
    },
      );
    }
  return {getPayments,getSale,postSale,getSaleResource,postSaleResource,postSaleResourcePax,postSaleStatus,postSaleDeliveryStatus,postSaleTarget,getSalePayments,postSalePayments,postSalePaymentsOffline,postSaleDiscountUpdate,getSales,getSalesSummary,getSalesPage,postSaleItemOutofstock,postSaleDeliveryMode,getSalesLedger,postSalesLoyalty,postSalesLoyaltyRedeem,postSalesLoyaltyVerifyRedeem,postSalesOffers,postSalesOffersRedeem,postSalesOffersVerifyRedeem}};
export type GetPaymentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getPayments']>>>
export type GetSaleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSale']>>>
export type PostSaleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSale']>>>
export type GetSaleResourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSaleResource']>>>
export type PostSaleResourceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleResource']>>>
export type PostSaleResourcePaxResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleResourcePax']>>>
export type PostSaleStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleStatus']>>>
export type PostSaleDeliveryStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleDeliveryStatus']>>>
export type PostSaleTargetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleTarget']>>>
export type GetSalePaymentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSalePayments']>>>
export type PostSalePaymentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalePayments']>>>
export type PostSalePaymentsOfflineResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalePaymentsOffline']>>>
export type PostSaleDiscountUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleDiscountUpdate']>>>
export type GetSalesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSales']>>>
export type GetSalesSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSalesSummary']>>>
export type GetSalesPageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSalesPage']>>>
export type PostSaleItemOutofstockResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleItemOutofstock']>>>
export type PostSaleDeliveryModeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSaleDeliveryMode']>>>
export type GetSalesLedgerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['getSalesLedger']>>>
export type PostSalesLoyaltyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesLoyalty']>>>
export type PostSalesLoyaltyRedeemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesLoyaltyRedeem']>>>
export type PostSalesLoyaltyVerifyRedeemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesLoyaltyVerifyRedeem']>>>
export type PostSalesOffersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesOffers']>>>
export type PostSalesOffersRedeemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesOffersRedeem']>>>
export type PostSalesOffersVerifyRedeemResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSale>['postSalesOffersVerifyRedeem']>>>
